/**
 * MCP Page Explorer
 * Interactive tool to explore web pages before writing Page Objects
 */

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

export interface PageElement {
  type: string;
  label: string;
  selector?: string;
  role?: string;
  box?: string;
}

export class MCPPageExplorer {
  private client: Client | null = null;

  async connect(): Promise<void> {
    this.client = new Client(
      { name: 'page-explorer', version: '1.0.0' },
      { capabilities: {} }
    );

    const transport = new StdioClientTransport({
      command: 'npx',
      args: ['@playwright/mcp@latest', '--config', 'playwright-mcp-config.json', '--headless'],
    });

    await this.client.connect(transport);
  }

  async explorePage(url: string): Promise<{
    url: string;
    title: string;
    elements: PageElement[];
    snapshot: string;
  }> {
    if (!this.client) throw new Error('Not connected');

    // Navigate
    await this.client.callTool({
      name: 'browser_navigate',
      arguments: { url }
    });

    // Get snapshot
    const result = await this.client.callTool({
      name: 'browser_snapshot',
      arguments: {}
    });

    const snapshotText = result.content?.[0]?.text || '';

    // Parse elements
    const elements: PageElement[] = [];

    // Extract all interactive elements
    const patterns = [
      { regex: /textbox "([^"]+)" \[ref=([^\]]+)\]/g, type: 'textbox' },
      { regex: /button "([^"]+)" \[ref=([^\]]+)\]/g, type: 'button' },
      { regex: /link "([^"]+)" \[ref=([^\]]+)\]/g, type: 'link' },
      { regex: /checkbox "([^"]+)" \[ref=([^\]]+)\]/g, type: 'checkbox' },
      { regex: /heading "([^"]+)" \[level=(\d+)\]/g, type: 'heading' },
    ];

    patterns.forEach(({ regex, type }) => {
      const matches = snapshotText.matchAll(regex);
      for (const match of matches) {
        elements.push({
          type,
          label: match[1],
          selector: match[2],
        });
      }
    });

    const titleMatch = snapshotText.match(/Page Title: ([^\n]+)/);
    const title = titleMatch ? titleMatch[1] : '';

    return {
      url,
      title,
      elements,
      snapshot: snapshotText
    };
  }

  async generatePageObject(url: string, className: string): Promise<string> {
    const pageData = await this.explorePage(url);

    let code = `import { Page, Locator } from '@playwright/test';\n\n`;
    code += `/**\n`;
    code += ` * Page Object for: ${pageData.title}\n`;
    code += ` * URL: ${url}\n`;
    code += ` * Generated by MCP Page Explorer\n`;
    code += ` */\n`;
    code += `export class ${className} {\n`;
    code += `  readonly page: Page;\n\n`;

    // Add locators for each element
    pageData.elements.forEach(el => {
      const propertyName = el.label
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '');

      code += `  readonly ${propertyName}: Locator;\n`;
    });

    code += `\n  constructor(page: Page) {\n`;
    code += `    this.page = page;\n\n`;

    // Initialize locators
    pageData.elements.forEach(el => {
      const propertyName = el.label
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '');

      // Try to guess selector
      const selector = `'[data-test="${propertyName}"]'`; // Placeholder
      code += `    this.${propertyName} = page.locator(${selector}); // TODO: Update selector\n`;
    });

    code += `  }\n\n`;

    code += `  async goto(): Promise<void> {\n`;
    code += `    await this.page.goto('${url}');\n`;
    code += `  }\n`;

    code += `}\n`;

    return code;
  }

  async takeScreenshot(filename: string): Promise<void> {
    if (!this.client) throw new Error('Not connected');

    await this.client.callTool({
      name: 'browser_screenshot',
      arguments: { fullPage: true }
    });

    console.log(`📸 Screenshot saved to: mcp-output/screenshots/${filename}`);
  }

  async close(): Promise<void> {
    if (this.client) {
      await this.client.callTool({
        name: 'browser_close',
        arguments: {}
      });
      await this.client.close();
    }
  }
}

// CLI Usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const url = process.argv[2];
  const className = process.argv[3] || 'GeneratedPage';

  if (!url) {
    console.error('Usage: node mcpPageExplorer.js <url> [className]');
    process.exit(1);
  }

  const explorer = new MCPPageExplorer();

  (async () => {
    try {
      await explorer.connect();
      console.log(`\n🔍 Exploring: ${url}\n`);

      const pageData = await explorer.explorePage(url);

      console.log(`📄 Page: ${pageData.title}`);
      console.log(`🔗 URL: ${pageData.url}`);
      console.log(`📊 Found ${pageData.elements.length} interactive elements:\n`);

      pageData.elements.forEach((el, i) => {
        console.log(`  ${i + 1}. [${el.type}] "${el.label}"`);
      });

      console.log(`\n📝 Generating Page Object class: ${className}\n`);
      const pageObjectCode = await explorer.generatePageObject(url, className);

      console.log('─'.repeat(60));
      console.log(pageObjectCode);
      console.log('─'.repeat(60));

      await explorer.close();
      process.exit(0);
    } catch (error) {
      console.error('❌ Error:', error);
      await explorer.close();
      process.exit(1);
    }
  })();
}
