/**
 * MCP Test Generator
 * Uses Playwright MCP to explore pages and generate test scaffolding
 */

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import * as fs from 'fs';
import * as path from 'path';

export interface TestGenerationConfig {
  url: string;
  testName: string;
  outputPath?: string;
  includeAssertions?: boolean;
}

export class MCPTestGenerator {
  private client: Client | null = null;
  private transport: StdioClientTransport | null = null;

  async connect(): Promise<void> {
    console.log('🔌 Connecting to Playwright MCP...');

    this.client = new Client(
      {
        name: 'qa-test-generator',
        version: '1.0.0',
      },
      {
        capabilities: {
          roots: {
            listChanged: false
          }
        },
      }
    );

    this.transport = new StdioClientTransport({
      command: 'npx',
      args: ['@playwright/mcp@latest', '--config', 'playwright-mcp-config.json', '--headless'],
    });

    await this.client.connect(this.transport);
    console.log('✅ Connected to MCP\n');
  }

  async explorePage(url: string): Promise<{
    title: string;
    elements: any[];
    forms: any[];
    buttons: any[];
  }> {
    if (!this.client) throw new Error('MCP client not connected');

    console.log(`🌐 Navigating to: ${url}`);
    await this.client.callTool({
      name: 'browser_navigate',
      arguments: { url }
    });

    console.log('📸 Getting page snapshot...');
    const snapshot = await this.client.callTool({
      name: 'browser_snapshot',
      arguments: {}
    });

    const snapshotText = snapshot.content?.[0]?.text || '';

    // Parse snapshot to extract elements
    const elements: any[] = [];
    const forms: any[] = [];
    const buttons: any[] = [];

    // Extract textboxes (inputs)
    const inputMatches = snapshotText.matchAll(/textbox "([^"]+)" \[ref=([^\]]+)\]/g);
    for (const match of inputMatches) {
      elements.push({ type: 'input', label: match[1], ref: match[2] });
    }

    // Extract buttons
    const buttonMatches = snapshotText.matchAll(/button "([^"]+)" \[ref=([^\]]+)\]/g);
    for (const match of buttonMatches) {
      buttons.push({ type: 'button', label: match[1], ref: match[2] });
      elements.push({ type: 'button', label: match[1], ref: match[2] });
    }

    // Extract page title
    const titleMatch = snapshotText.match(/Page Title: ([^\n]+)/);
    const title = titleMatch ? titleMatch[1] : 'Untitled Page';

    console.log(`✅ Found ${elements.length} interactive elements\n`);

    return {
      title,
      elements,
      forms,
      buttons
    };
  }

  async generateTest(config: TestGenerationConfig): Promise<string> {
    const { url, testName, includeAssertions = true } = config;

    const pageData = await this.explorePage(url);

    // Generate test code
    let testCode = `import { test, expect } from '@playwright/test';\n\n`;
    testCode += `/**\n`;
    testCode += ` * Generated test for: ${pageData.title}\n`;
    testCode += ` * URL: ${url}\n`;
    testCode += ` * Generated by: MCP Test Generator\n`;
    testCode += ` */\n\n`;
    testCode += `test.describe('${testName}', () => {\n`;
    testCode += `  test('should interact with ${pageData.title}', { tag: '@mcp-generated' }, async ({ page }) => {\n`;
    testCode += `    // Navigate to page\n`;
    testCode += `    await page.goto('${url}');\n\n`;

    if (includeAssertions) {
      testCode += `    // Verify page loaded\n`;
      testCode += `    await expect(page).toHaveTitle(/${pageData.title}/);\n\n`;
    }

    // Add interactions for found elements
    if (pageData.elements.length > 0) {
      testCode += `    // Interactive elements found:\n`;
      pageData.elements.forEach((el, index) => {
        testCode += `    // ${index + 1}. ${el.type}: "${el.label}"\n`;
      });
      testCode += `\n`;
      testCode += `    // TODO: Add interactions here\n`;
      testCode += `    // Example:\n`;
      if (pageData.elements.some(el => el.type === 'input')) {
        const firstInput = pageData.elements.find(el => el.type === 'input');
        testCode += `    // await page.fill('[data-test="username"]', 'test_value');\n`;
      }
      if (pageData.buttons.length > 0) {
        testCode += `    // await page.click('[data-test="login-button"]');\n`;
      }
    }

    testCode += `  });\n`;
    testCode += `});\n`;

    return testCode;
  }

  async saveTest(testCode: string, outputPath: string): Promise<void> {
    const fullPath = path.resolve(outputPath);
    const dir = path.dirname(fullPath);

    // Ensure directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(fullPath, testCode, 'utf-8');
    console.log(`✅ Test saved to: ${fullPath}\n`);
  }

  async close(): Promise<void> {
    if (this.client) {
      await this.client.callTool({
        name: 'browser_close',
        arguments: {}
      });
      await this.client.close();
      console.log('🔒 MCP connection closed');
    }
  }
}

// CLI Usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const url = process.argv[2];
  const testName = process.argv[3] || 'Generated Test';
  const outputPath = process.argv[4] || 'tests/generated/test.spec.ts';

  if (!url) {
    console.error('Usage: node mcpTestGenerator.js <url> [testName] [outputPath]');
    console.error('Example: node mcpTestGenerator.js https://www.saucedemo.com "Login Tests" tests/generated/login.spec.ts');
    process.exit(1);
  }

  const generator = new MCPTestGenerator();

  (async () => {
    try {
      await generator.connect();
      const testCode = await generator.generateTest({
        url,
        testName,
        outputPath,
        includeAssertions: true
      });

      console.log('📄 Generated Test Code:\n');
      console.log('─'.repeat(60));
      console.log(testCode);
      console.log('─'.repeat(60));

      await generator.saveTest(testCode, outputPath);
      console.log('\n🎉 Test generation complete!');
      await generator.close();
      process.exit(0);
    } catch (error) {
      console.error('❌ Error:', error);
      await generator.close();
      process.exit(1);
    }
  })();
}
