name: Chrome > Saucedemo UI Playwright Tests with Typescript
on:
  #schedule:
    # Schedule to run 8 times a day at specific hours in UTC+2
    #- cron: '0 0,3,6,9,12,15,18,21 * * *'
  push:
    branches: 
      - main
permissions:
  contents: write
  issues: write
  statuses: write
  deployments: write
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      uses: ./.github/actions/run-playwright-tests
      with:
        environment: 'DEMO'
        tag: "@critical"
        browser: "chromium"
        shardIndex: ${{ matrix.shardIndex }}
        shardTotal: ${{ matrix.shardTotal }}

  merge-reports:
    needs: [run-ui-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Download All Reports
        uses: actions/download-artifact@v4
        with:
          path: all-reports
          pattern: saucedemo-report-*
          merge-multiple: false

      - name: Merge All CTRF Test Summary Results
        shell: bash
        run: |
          mkdir -p ctrf-reports
          find all-reports/saucedemo-report-*/test-results -name 'ctrf-report.json' | while read file; do
            cp "$file" "ctrf-reports/$(basename $(dirname $(dirname $file)))-ctrf-report.json"
          done
          npx merge-ctrf ctrf-reports

      - name: Publish CTRF Test Summary Results
        shell: bash
        run: npx github-actions-ctrf ctrf-reports/ctrf-report.json
        if: always()